# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

force_bundle_iter <- function(edges_xy, elist, K, C, P, P_rate, S, I, I_rate, compatibility_threshold, eps) {
    .Call(`_edgebundle_force_bundle_iter`, edges_xy, elist, K, C, P, P_rate, S, I, I_rate, compatibility_threshold, eps)
}

criterion_angular_resolution <- function(adj, xy) {
    .Call(`_edgebundle_criterion_angular_resolution`, adj, xy)
}

criterion_edge_length <- function(el, xy, lg) {
    .Call(`_edgebundle_criterion_edge_length`, el, xy, lg)
}

criterion_balanced_edge_length <- function(adj_deg2, xy) {
    .Call(`_edgebundle_criterion_balanced_edge_length`, adj_deg2, xy)
}

criterion_line_straightness <- function() {
    .Call(`_edgebundle_criterion_line_straightness`)
}

criterion_octilinearity <- function(el, xy) {
    .Call(`_edgebundle_criterion_octilinearity`, el, xy)
}

layout_as_metro_iter <- function(adj, el, adj_deg2, xy, bbox, l, gr, w, bsize) {
    .Call(`_edgebundle_layout_as_metro_iter`, adj, el, adj_deg2, xy, bbox, l, gr, w, bsize)
}

