# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

force_bundle_iter <- function(edges_xy, elist, K, C, P, P_rate, S, I, I_rate, compatibility_threshold, eps) {
    .Call(`_edgebundle_force_bundle_iter`, edges_xy, elist, K, C, P, P_rate, S, I, I_rate, compatibility_threshold, eps)
}

